version: "3.3"

services:
  app:
    container_name: jet-terabox
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - TERABOX_API_URL=http://terabox-api:5000/api
    depends_on:
      - terabox-api

  terabox-api:
    container_name: terabox-api
    build:
      context: ./terabox-api
      dockerfile: dockerfile
    restart: always
    ports:
      - "5000:5000"